server:
  port: 8761
  
eureka:
  instance:
   hostname: http://eureka-server-mysql1.b9ad.pro-us-east-1.openshiftapps.com 
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: true
    fetch-registry: true