server:
  port: 8080
  
eureka:
  instance:
   hostname: http://eureka-server-spring-project.b9ad.pro-us-east-1.openshiftapps.com
  client:
    serviceUrl:
      defaultZone: ${eureka.instance.hostname}/eureka/
    register-with-eureka: false
    fetch-registry: false