server:
  port: 8761
  
eureka:
  instance:
   hostname: server.eureka.svc 
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: true
    fetch-registry: true